server:
  port: 9001
#  ssl:
#    enabled: true
#    key-store: security/wisengage-keystore.p12
#    key-store-password: changeit
#    #key-store-password: bHC/jakBgiH6sr5zvO8PFA==
#    key-store-type: PKCS12
#    key-alias: wisengage-key
#    key-password: changeit
#    #key-password: bHC/jakBgiH6sr5zvO8PFA==


spring:
  main:
    web-application-type: reactive
  allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#Eureka Discovery Server Register
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true