server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: native

eureka:
  instance:
    hostname: configserver
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
